[metadata]
id = "test-package"
project_url = "https:/_Software_Location_REMOVE_OR_FILL_OUT_"
summary = ""
license = "MIT"

[metadata.chocolatey]
authors = ["WormieCorp"]
description = "Some description"
