name: Build Project

on:
  push:
    branches: [master, develop, "multi-plat"]
    tags-ignore:
      - "*"
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: i686-pc-windows-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - name: Build projects with all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --locked
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            target/release/pkg-upd
            target/release/pkg-upd.exe
      - name: Test projects with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --locked
