name: Build Project

on:
  push:
    branches: [master, develop]
    tags-ignore:
      - "*"
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.toml') }}
      - name: Build projects with all features
        run: cargo build --release --all-features --locked
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            target/release/aer
            target/release/aer-ver
            target/release/aer-web
            target/release/*.bin
            target/release/*.exe
      - name: Test projects with all features
        run: |
          if ($IsWindows) { Set-ExecutionPolicy RemoteSigned -Force }
          cargo test --release --all-features --locked
        shell: pwsh
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest] # Coverage report do not work on Windows
        features: [all, human, none]

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.toml') }}
      - name: Run unit tests with coverage report and all features
        if: ${{ matrix.features == 'all' }}
        uses: Swatinem/fucov@v1
      - name: Run unit tests with coverage report and no features
        if: ${{ matrix.features == 'none' }}
        uses: Swatinem/fucov@v1
        with:
          args: --workspace --no-default-features
      - name: Run unit tests with coverage report and features ${{ matrix.features }}
        if: ${{ matrix.features != 'all' && matrix.features != 'none' }}
        uses: Swatinem/fucov@v1
        with:
          args: --workspace --no-default-features --features ${{ matrix.features }}
      - name: Upload coverage report
        uses: codecov/codecov-action@v2.0.2
        with:
          directory: coverage
