name: Build Project

on:
  push:
    branches: [master, develop, "multi-plat"]
    tags-ignore:
      - "*"
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build projects with all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --locked
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            target/release/pkg-upd
            target/release/pkg-upd.bin
            target/release/pkg-upd.exe
      - name: Test projects with all features (windows)
        if: ${{ runner.os != 'Windows' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --locked
        run: Set-ExecutionPolicy Unrestricted -Force
      - name: Test projects with all features (windows)
        if: ${{ runner.os == 'Windows' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --locked
        run: Set-ExecutionPolicy Unrestricted -Force
        shell: pwsh
